name: Deploy

on:
  push:
    branches:
      - master
      - develop
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and update Docker image       # 寫法一：用指令
        run: |
          docker build -t fangchiawen/cinepos_frontend:${{ github.sha }} .
          docker images
          docker push fangchiawen/cinepos_frontend:${{ github.sha }}
      # - name: Build and update Docker image     # 寫法二：用套件
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     push: true
      #     tags: fangchiawen/cinepos_frontend:${{ github.sha }}

      - name: Run Docker image
        run: |
          docker run -d --rm -p 4200:4200 fangchiawen/cinepos_frontend:latest
      - name: Set Git identity
        run: |
          git config --global user.email "fangchiawen@gmail.com"
          git config --global user.name "chiawen81"
      - name: Deploy the app to GitHub Pages
        run: |
          npm install angular-cli-ghpages
          npm run build:patch
          npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
